#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*
Random numbers generated by the computer are stored in two different memory regions.
Memory sizes are different from each other.
Accordingly, write a C program that combines these two arrays into a single array using dynamic memory and displays it to the screen.
*/

int main()
{
	int number1, number2, *array1, *array2, *array3, j, i;
    printf("Enter the Number of Elements of the First Array: ");
    scanf("%d", &number1);
    printf("Enter the Number of Elements of the Second Array: ");
    scanf("%d", &number2);

    array1 = (int *) malloc(number1*sizeof(int));
    array2 = (int *) malloc(number2*sizeof(int));
    array3 = (int *) malloc((number1+number2)*sizeof(int));
    printf("-------------------------\n");

    srand(time(0));
    for(i = 0; i<number1; i++){
		*(array1+i) = rand()%100+1;
		*(array3+i) = *(array1+i);
		printf("%d ", *(array1+i));
    }

        printf("\n-------------------------\n");

	for(i = 0; i<number2; i++){
		*(array2+i) = rand()%100+1;
		printf("%d ", *(array2+i));
    }

	printf("\n-------------------------\n");

	for(i = number1, j = 0; i<number1 + number2; i++, j++){
		*(array3+i) = *(array2+j);
    }

	for(i = 0; i<number1 + number2; i++){
		printf("%d ", *(array3+i));
    }

    printf("\n-------------------------\n");

    free(array1);
    free(array2);
    free(array3);
    return 0;
}
