#include <stdio.h>
#include <stdlib.h>
#include <time.h>

/*
Write a C program that allows N integers randomly generated by the computer to be written to the memory,
then the values read from the memory to the number.txt file and the values read from the file to be listed on the screen.
*/

int main()
{
  FILE *file;
   int *array, number, i, character;

   printf("Enter a number: ");
   scanf("%d", &number);
   array = (int *)malloc(number*sizeof(int));
   file = fopen("Number.txt", "w");
   srand(time(0));
   printf("-------------------------\nNumbers Generated\n-------------------------\n");

   for(i=0;i<number;i++)
   {
       *(array+i)=rand()%100+1;
       fprintf(file,"%d ",*(array+i));
       printf("%d ",*(array+i));
   }
   fclose(file);
   printf("\n-------------------------\nNumbers Read\n-------------------------\n");

   file=fopen("Number.txt", "r");
   do
   {
       character = getc(file);
       if(character !=EOF)
       {
           putchar(character);
       }

   }while(character != EOF);
   fclose(file);
   free(array);

    return 0;
}
