#include <stdio.h>
#include <stdlib.h>
#include <time.h>
/*
N integers randomly generated by the computer are kept in an array.
Write a C program that arranges array elements from smallest to largest with the help of a recursive function.
*/

void Sort_Array(int number, int array[]){
	int temp;
	if(number > 0){
		for(int i = 0; i < number; i++){
			if(array[i]>array[i+1]){
				temp = array[i+1];
				array[i+1] = array[i];
				array[i] = temp;
			}
		}
		Sort_Array(number-1, array);
	}


}

int main()
{
	int number;
    printf("Enter a number of array: ");
    scanf("%d", &number);
    int array[number];

    printf("-----------------------\n");
    srand(time(0));
    for(int i = 0; i < number; i++){
		array[i] = rand()%100+1;
		printf("%d ", *(array+i));
    }

    printf("\n-----------------------\n");
    Sort_Array(number-1, array);
        for(int i = 0; i < number; i++){
		printf("%d ", *(array+i));
    }
    return 0;
}
