#include <stdio.h>
#include <stdlib.h>

/*
N numbers randomly generated by the computer are kept in an array. Write a C program that allows an integer taken from the keyboard
to be added to the relevant row by specifying the array element number into the array.
*/

void new_element(int sequence[], int number, int element, int order){
    int i = number - 1;
    if(order <= number+1){
        while(i >= order-1){
            sequence[i+1] = sequence[i];
            i--;
        }
        sequence[order-1] = element;
    }
    else{
        printf("Please enter a valid sequence number!!!");
    }
}

int main()
{
    int number, element, i = 0, order;
    printf("Enter the number of elements of the array: ");
    scanf("%d", &number);
    printf("Enter the number to be added and the sequence number of the number:");
    scanf("%d %d", &element, &order);
    int sequence[number];
    srand(time(0));
    printf("-----------------------\n");

    while(i < number){
        sequence[i] = rand()%100;
        printf("%d ", sequence[i]);
        i++;
    }
    printf("\n-----------------------\n");
    new_element(sequence, number, element, order);

    i = 0;
    while(i <= number){
        printf("%d ", sequence[i]);
        i++;
    }

    return 0;
}
