#include <stdio.h>
#include <stdlib.h>

/*
N numbers randomly generated by the computer are kept in an array. Accordingly, write the C program as
a function that allows the array elements to be ordered from smallest to largest by using the function prototype given below.
void sort(int A[], int number)
*/

void sort(int sequence[], int number){
    int temp, j = 0, i;
    while(j < number-1){
        i = 0;
        while(i < number-1-j){
            if(sequence[i] >= sequence[i+1]){
                temp = sequence[i];
                sequence[i] = sequence[i+1];
                sequence[i+1] = temp;
            }
            i++;
        }
        j++;
    }
    sequence[number] = '\0';
    i = 0;
    while(sequence[i]){
        printf("%d ", sequence[i]);
        i++;
    }
    printf("\n-------------------------------");
}



int main()
{
    int number, i = 0;
    printf("Enter the Number of Elements of the Array: ");
    scanf("%d", &number);
    int sequence[number];
    srand(time(0));
    printf("\n-------------------------------\n");
    while(i < number){
        sequence[i] = rand()%100;
        printf("%d ", sequence[i]);
        i++;
    }
    printf("\n-------------------------------\n");
    sort(sequence, number);
    return 0;
}
