#include <stdio.h>
#include <stdlib.h>
/*
N numbers randomly generated by the computer are kept in an array. Write a C program using a function,
which enables the deletion of the sequence value in the relevant row by entering the sequence number of a desired value in the array.
*/

void delete_element(int sequence[150], int number, int element){
    int i = 0;
    while(i < (number - 1)){
        if(i >= (element - 1)){
            sequence[i]=sequence[i+1];
        }
        i++;
    }
    sequence[i] = '\0';
    i = 0;
    printf("\n--------------------\nAfter deletion of the number in the array: ");
    while(i < (number - 1)){
        printf("%d ", sequence[i]);
        i++;
    }
}

int main()
{
    int number, i = 0, element;
    printf("Enter the Number of Elements of the Array: ");
    scanf("%d", &number);
    printf("\nEnter the Sequence Number of the Element to be Deleted: ");
    scanf("%d", &element);
    int sequence[number];
    srand(time(0));
    printf("\n--------------------\n");
    while(i < number){
        sequence[i] = rand()%100;
        printf("%d ", sequence[i]);
        i++;
    }
    delete_element(sequence, number, element);
    return 0;
}
