#include <stdio.h>
#include <stdlib.h>
/*
N numbers randomly generated by the computer are kept in an array.
Write a C program to find the maximum and minimum values in an array using two separate functions.
*/

int find_max(int sequence[150], int number) {
    int i = 1, max = sequence[0];
    while(i < number) {
        if(sequence[i] >= max) {
            max = sequence[i];
        }
        i++;
    }
    return max;
}

int find_min(int sequence[150], int number) {
    int i = 1, min = sequence[0];
    while(i < number) {
        if(sequence[i] <= min) {
            min = sequence[i];
        }
        i++;
    }
    return min;
}

int main() {
    int number, i = 0;
    printf("Enter a number: ");
    scanf("%d", &number);
    int sequence[number];
    srand(time(0));
    printf("-----------------------\n");
    while(i < number) {
        sequence[i] = rand()%100;
        printf("%d ", sequence[i]);
        i++;
    }
    printf("\n-----------------------\nLargest element of array: %d\n-----------------------\nSmallest element of the array: %d", find_max(sequence, number), find_min(sequence,number));

    return 0;
}
